
EXEC   = adsmooth.so

SRCS   = main.c ngbtree2d.c  \
	 nrutil.c selectb.c sort_flt.c sort2_flt.c 


OBJS   = $(SRCS:.c=.o)
INCL   = allvars.h   \
	 nrutil.h


CFLAGS =  -xarch=v9

LIBS   =   

CC     =  cc 

$(EXEC): $(OBJS) 
#	ld -shared $(OBJS) $(LIBS)  -o $(EXEC)
	ld -G $(OBJS) $(LIBS)  -o $(EXEC)


$(OBJS): $(INCL) 



clean:
	rm $(OBJS) $(EXEC)










