
EXEC   = colors

OBJS   = main.o colors.o

INCL   = colors.h 


CFLAGS =  -fPIC -m64 -O3 -g  #  -Wall   -I/usr/include
LNKCMD =  ld -m elf_x86_64  -L/usr/lib64  -shared

LIBS   =  -lm

CC     =   c++   # g++

$(EXEC): $(OBJS)
	$(CC) -m elf_x86_64  -L/usr/lib64  -shared $(OBJS) $(LIBS)  -o $(EXEC)


$(OBJS): $(INCL) 


.PHONY : clean
clean:
	rm -f $(OBJS) $(EXEC)

