
EXEC   = colors

OBJS   = main.o colors.o

INCL   = colors.h 


CFLAGS =  -fPIC -m32 -O3 -g  #  -Wall   -I/usr/include

LIBS   =  -lm

CC     =   c++   # g++

$(EXEC): $(OBJS)
	$(CC) -L/usr/lib  -L/usr/local/lib  -shared $(OBJS) $(LIBS)  -o $(EXEC)


$(OBJS): $(INCL) 


.PHONY : clean
clean:
	rm -f $(OBJS) $(EXEC)

